spring:
  profiles:
    active: qa

---
spring:
  profiles: dev

server:
  port: 9090

default:
  course:
    name: SAP HANA
    chapterCount: 3

course:
  name: AWS and DOCKER
  chapterCount: 45
  rating: 5
  author: Rafael Nadal

---
spring:
  profiles: qa

server:
  port: 9191

default:
  course:
    name: SAP HANA
    chapterCount: 3

course:
  name: SPRING BOOT
  chapterCount: 450
  rating: 10
  author: Tim Buchalka